# Generated by Django 2.1.4 on 2020-05-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='score',
            field=models.IntegerField(default=1),
        ),
    ]
