# Generated by Django 2.1.4 on 2020-05-05 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='karma',
        ),
    ]
