# Generated by Django 2.1.4 on 2020-05-30 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_remove_profile_karma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='score',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
